export const CLIENTES_SEED = [
  { id: 'atl', razaoSocial: 'Atlântico Distribuidora Ltda', nomeCurto: 'Atlântico Distribuidora', cnpj: '12.345.678/0001-90', municipio: 'Salvador', contatoPrincipal: 'Hugo Andrade (sócio)', estabelecimentosQtd: 2 },
  { id: 'ges', razaoSocial: 'Gesso Forte Ltda', nomeCurto: 'Gesso Forte', cnpj: '23.456.789/0001-01', municipio: 'Salvador', contatoPrincipal: 'Márcio Reis', estabelecimentosQtd: 1 },
  { id: 'spa', razaoSocial: 'Spazio Comércio Ltda', nomeCurto: 'Spazio Comércio', cnpj: '34.567.890/0001-12', municipio: 'Lauro de Freitas', contatoPrincipal: 'Tânia Vieira (financeiro)', estabelecimentosQtd: 1 },
  { id: 'v25', razaoSocial: 'V25 Serviços Ltda', nomeCurto: 'V25 Serviços', cnpj: '45.678.901/0001-23', municipio: 'Camaçari', contatoPrincipal: 'Rose Santos', estabelecimentosQtd: 1 },
  { id: 'loy', razaoSocial: 'Loyola Fonoaudiologia Ltda', nomeCurto: 'Loyola Fonoaudiologia', cnpj: '56.789.012/0001-34', municipio: 'Salvador', contatoPrincipal: 'Graziela Loyola', estabelecimentosQtd: 1 },
  { id: 'sem', razaoSocial: 'Instituto Semear', nomeCurto: 'Instituto Semear', cnpj: '67.890.123/0001-45', municipio: 'Salvador', contatoPrincipal: 'Diretoria', estabelecimentosQtd: 1 },
  { id: 'tec', razaoSocial: 'Techsale Comércio Ltda', nomeCurto: 'Techsale Comércio', cnpj: '78.901.234/0001-56', municipio: 'Salvador', contatoPrincipal: 'Mônica Prado', estabelecimentosQtd: 1 },
  { id: 'esc', razaoSocial: 'Escola Encontro Infantil Ltda', nomeCurto: 'Escola Encontro Infantil', cnpj: '89.012.345/0001-67', municipio: 'Salvador', contatoPrincipal: 'Helberte Lima', estabelecimentosQtd: 1 },
  { id: 'ant', razaoSocial: 'Antônio & Filho Ltda', nomeCurto: 'Antônio & Filho', cnpj: '90.123.456/0001-78', municipio: 'Salvador', contatoPrincipal: 'Rose Almeida', estabelecimentosQtd: 1 },
  { id: 'mis', razaoSocial: 'Missão Pescadores', nomeCurto: 'Missão Pescadores', cnpj: '01.234.567/0001-89', municipio: 'Salvador', contatoPrincipal: 'Pastor João', estabelecimentosQtd: 1 },
  { id: 'mar', razaoSocial: 'Marco Aurélio Consultoria (em abertura)', nomeCurto: 'Marco Aurélio Consultoria', cnpj: '—', municipio: 'Salvador', contatoPrincipal: 'Marco Aurélio', estabelecimentosQtd: 0 }
];

export const DEMANDAS_SEED = [
  { id: 'D-063', data: '02/10/2026', canal: 'E-mail' as const, clienteNome: 'Loyola Fonoaudiologia', solicitante: 'Graziela Loyola', descricao: 'Precisamos da certidão negativa federal para licitação até o dia 09.', anexos: '', status: 'Nova' as const, processosVinculados: [] },
  { id: 'D-062', data: '02/10/2026', canal: 'DTE' as const, clienteNome: 'Atlântico Distribuidora', solicitante: 'DT-e Bahia', descricao: 'Intimação para apresentação de livros fiscais — filial Camaçari.', anexos: '', status: 'Em triagem' as const, processosVinculados: [] },
  { id: 'D-064', data: '01/10/2026', canal: 'Telefone' as const, clienteNome: 'Escola Encontro Infantil', solicitante: 'Helberte Lima', descricao: 'Dúvida sobre prazo para encerrar a inscrição municipal após a baixa.', anexos: '', status: 'Nova' as const, processosVinculados: [] },
  { id: 'D-059', data: '01/10/2026', canal: 'Interno' as const, clienteNome: 'Atlântico Distribuidora', solicitante: 'Paulo Lima', descricao: 'Verificar novos PAFs do mês.', anexos: '', status: 'Convertida' as const, processosVinculados: ['P-113'] },
  { id: 'D-058', data: '29/09/2026', canal: 'WhatsApp' as const, clienteNome: 'Techsale Comércio', solicitante: 'Mônica Prado', descricao: 'Certificado da empresa vence dia 20.', anexos: '', status: 'Convertida' as const, processosVinculados: ['P-115'] },
  { id: 'D-057', data: '27/09/2026', canal: 'DTE' as const, clienteNome: 'Spazio Comércio', solicitante: 'DT-e Bahia', descricao: 'Comunicado de malha — energia adquirida no mercado livre.', anexos: '', status: 'Convertida' as const, processosVinculados: ['P-114'] },
  { id: 'D-055', data: '25/09/2026', canal: 'WhatsApp' as const, clienteNome: 'Marco Aurélio Consultoria', solicitante: 'Marco Aurélio', descricao: 'Quero abrir minha consultoria.', anexos: '', status: 'Convertida' as const, processosVinculados: ['P-112'] },
  { id: 'D-052', data: '22/09/2026', canal: 'WhatsApp' as const, clienteNome: 'Atlântico Distribuidora', solicitante: 'Hugo Andrade', descricao: 'Incluir a Jales Consultoria como sócia da Atlântico.', anexos: '', status: 'Convertida' as const, processosVinculados: ['P-101'] },
  { id: 'D-051', data: '21/09/2026', canal: 'E-mail' as const, clienteNome: 'Techsale Comércio', solicitante: 'Mônica Prado', descricao: 'Levantar todos os débitos antes de pedir financiamento.', anexos: '', status: 'Convertida' as const, processosVinculados: ['P-108'] },
  { id: 'D-050', data: '20/09/2026', canal: 'E-mail' as const, clienteNome: 'Antônio & Filho', solicitante: 'Rose Almeida', descricao: 'Cancelar a NFS-e 1.284 emitida com valor errado.', anexos: '', status: 'Convertida' as const, processosVinculados: ['P-110'] },
  { id: 'D-048', data: '18/09/2026', canal: 'WhatsApp' as const, clienteNome: 'Gesso Forte', solicitante: 'Márcio Reis', descricao: 'Mudamos de endereço: alterar o contrato e emitir o alvará novo.', anexos: '', status: 'Convertida' as const, processosVinculados: ['P-102', 'P-103'] },
  { id: 'D-046', data: '16/09/2026', canal: 'E-mail' as const, clienteNome: 'Instituto Semear', solicitante: 'Diretoria', descricao: 'Cancelar nota emitida em duplicidade.', anexos: '', status: 'Convertida' as const, processosVinculados: ['P-107'] },
  { id: 'D-041', data: '12/09/2026', canal: 'WhatsApp' as const, clienteNome: 'V25 Serviços', solicitante: 'Rose Santos', descricao: 'Pedido repetido de senha NFS-e (já atendido pela D-040).', anexos: '', status: 'Arquivada' as const, processosVinculados: [] }
];

export const PROCESSOS_SEED = [
  { id: 'P-101', clienteId: 'atl', clienteNome: 'Atlântico Distribuidora', cnpj: '12.345.678/0001-90', estabelecimento: 'Matriz', codigoProcedimento: '05', titulo: 'Alteração — inclusão de sócia', situacao: 'cli' as const, diasParado: 4, etapaAtual: 4, etapasTotal: 6, proximaAcao: 'Cobrar assinatura do sócio', responsavel: 'Matheus', prazoInterno: '05/10/2026', marcos: [{ tipo: 'Enviado' as const, data: '30/09' }], motivoAguardando: 'Assinatura de Jales Consultoria e pagamento da taxa', demandaOrigemId: 'D-052', orgao: 'JUCEB', ultimaAtualizacao: '02/10' },
  { id: 'P-102', clienteId: 'ges', clienteNome: 'Gesso Forte', cnpj: '23.456.789/0001-01', estabelecimento: 'Matriz', codigoProcedimento: '05', titulo: 'Alteração de endereço', situacao: 'org' as const, diasParado: 3, etapaAtual: 5, etapasTotal: 6, proximaAcao: 'Consultar protocolo BAP2600456789', responsavel: 'Matheus', prazoInterno: '06/10/2026', marcos: [{ tipo: 'Pago' as const, data: '25/09' }, { tipo: 'Protocolado' as const, data: '29/09' }], motivoAguardando: 'Protocolo JUCEB BAP2600456789', protocoloAguardando: 'BAP2600456789', demandaOrigemId: 'D-048', orgao: 'JUCEB', ultimaAtualizacao: '02/10' },
  { id: 'P-103', clienteId: 'ges', clienteNome: 'Gesso Forte', cnpj: '23.456.789/0001-01', estabelecimento: 'Matriz', codigoProcedimento: '12', titulo: 'Alvará de funcionamento — Salvador', situacao: 'nao' as const, diasParado: 0, etapaAtual: 1, etapasTotal: 6, proximaAcao: 'Aguardar deferimento da alteração', responsavel: 'Matheus', prazoInterno: '20/10/2026', bloqueadoPorId: 'P-102', demandaOrigemId: 'D-048', orgao: 'SEFAZ Salvador', ultimaAtualizacao: '01/10' },
  { id: 'P-104', clienteId: 'spa', clienteNome: 'Spazio Comércio', cnpj: '34.567.890/0001-12', estabelecimento: 'Matriz', codigoProcedimento: '24', titulo: 'Atualização de DAE de PAF 2136870025', situacao: 'and' as const, diasParado: 0, etapaAtual: 5, etapasTotal: 6, proximaAcao: 'Emitir DAE atualizado na SEFAZ-BA', responsavel: 'Matheus', prazoInterno: '02/10/2026', demandaOrigemId: 'D-044', orgao: 'SEFAZ-BA', ultimaAtualizacao: '02/10' },
  { id: 'P-105', clienteId: 'v25', clienteNome: 'V25 Serviços', cnpj: '45.678.901/0001-23', estabelecimento: 'Matriz', codigoProcedimento: '33', titulo: 'Senha NFS-e — Camaçari', situacao: 'org' as const, diasParado: 9, etapaAtual: 3, etapasTotal: 6, proximaAcao: 'Ligar para a SEFAZ Camaçari', responsavel: 'Ana', prazoInterno: '30/09/2026', marcos: [{ tipo: 'Protocolado' as const, data: '23/09' }], motivoAguardando: 'Requerimento de senha nº 2026/0918', protocoloAguardando: '2026/0918', demandaOrigemId: 'D-040', orgao: 'SEFAZ Camaçari', ultimaAtualizacao: '25/09' },
  { id: 'P-106', clienteId: 'loy', clienteNome: 'Loyola Fonoaudiologia', cnpj: '56.789.012/0001-34', estabelecimento: 'Matriz', codigoProcedimento: '05', titulo: 'Mudança de UF Bahia → Goiás', situacao: 'and' as const, diasParado: 0, etapaAtual: 2, etapasTotal: 6, proximaAcao: 'Protocolar viabilidade na Junta de Goiás', responsavel: 'Matheus', prazoInterno: '08/10/2026', orgao: 'JUCEG', demandaOrigemId: 'D-049', ultimaAtualizacao: '01/10' },
  { id: 'P-107', clienteId: 'sem', clienteNome: 'Instituto Semear', cnpj: '67.890.123/0001-45', estabelecimento: 'Matriz', codigoProcedimento: '34', titulo: 'Cancelamento de NFS-e', situacao: 'nao' as const, diasParado: 0, etapaAtual: 1, etapasTotal: 6, proximaAcao: '', responsavel: '', prazoInterno: '', demandaOrigemId: 'D-046', orgao: 'SEFAZ Salvador', ultimaAtualizacao: '16/09' },
  { id: 'P-108', clienteId: 'tec', clienteNome: 'Techsale Comércio', cnpj: '78.901.234/0001-56', estabelecimento: 'Matriz', codigoProcedimento: '17', titulo: 'Diagnóstico de débitos', situacao: 'set' as const, diasParado: 2, etapaAtual: 5, etapasTotal: 6, proximaAcao: 'Carla validar valores retificados', responsavel: 'Carla', prazoInterno: '07/10/2026', setorAguardando: 'Fiscal', motivoAguardando: 'Validar valores retificados das DCTFWeb', orgao: 'Receita / SEFAZ-BA / Salvador', demandaOrigemId: 'D-051', ultimaAtualizacao: '01/10' },
  { id: 'P-109', clienteId: 'esc', clienteNome: 'Escola Encontro Infantil', cnpj: '89.012.345/0001-67', estabelecimento: 'Matriz', codigoProcedimento: '07', titulo: 'Baixa de empresa', situacao: 'nao' as const, diasParado: 0, etapaAtual: 1, etapasTotal: 6, proximaAcao: 'Levantar débitos e obrigações com os setores', responsavel: 'Ana', prazoInterno: '15/10/2026', demandaOrigemId: 'D-047', orgao: 'JUCEB', ultimaAtualizacao: '22/09' },
  { id: 'P-110', clienteId: 'ant', clienteNome: 'Antônio & Filho', cnpj: '90.123.456/0001-78', estabelecimento: 'Matriz', codigoProcedimento: '34', titulo: 'Cancelamento de nota fiscal', situacao: 'cli' as const, diasParado: 12, etapaAtual: 3, etapasTotal: 6, proximaAcao: 'Obter declaração do tomador', responsavel: 'Matheus', prazoInterno: '03/10/2026', motivoAguardando: 'Obter declaração do tomador', demandaOrigemId: 'D-050', orgao: 'SEFAZ Salvador', ultimaAtualizacao: '28/09' },
  { id: 'P-111', clienteId: 'mis', clienteNome: 'Missão Pescadores', cnpj: '01.234.567/0001-89', estabelecimento: 'Matriz', codigoProcedimento: '12', titulo: 'Alvará — regularizar pendências do CNPJ', situacao: 'org' as const, diasParado: 6, etapaAtual: 4, etapasTotal: 6, proximaAcao: 'Acompanhar nova viabilidade', responsavel: 'Ana', prazoInterno: '10/10/2026', marcos: [{ tipo: 'Exigência' as const, data: '24/09' }, { tipo: 'Protocolado' as const, data: '26/09' }], motivoAguardando: 'Nova viabilidade REGIN', demandaOrigemId: 'D-045', orgao: 'SEDUR', ultimaAtualizacao: '26/09' },
  { id: 'P-112', clienteId: 'mar', clienteNome: 'Marco Aurélio Consultoria', cnpj: '—', estabelecimento: 'Em abertura', codigoProcedimento: '03', titulo: 'Abertura de empresa', situacao: 'cli' as const, diasParado: 2, etapaAtual: 1, etapasTotal: 6, proximaAcao: 'Receber documentos dos sócios', responsavel: 'Matheus', prazoInterno: '09/10/2026', motivoAguardando: 'Documentos dos sócios', demandaOrigemId: 'D-055', orgao: 'JUCEB', ultimaAtualizacao: '01/10' },
  { id: 'P-113', clienteId: 'atl', clienteNome: 'Atlântico Distribuidora', cnpj: '12.345.678/0001-90', estabelecimento: 'Matriz', codigoProcedimento: '28', titulo: 'PAF estadual — verificar novos', situacao: 'and' as const, diasParado: 0, etapaAtual: 2, etapasTotal: 6, proximaAcao: 'Comparar com lista de 01/09', responsavel: 'Matheus', prazoInterno: '07/10/2026', demandaOrigemId: 'D-059', orgao: 'SEFAZ-BA', ultimaAtualizacao: '02/10' },
  { id: 'P-114', clienteId: 'spa', clienteNome: 'Spazio Comércio', cnpj: '34.567.890/0001-12', estabelecimento: 'Matriz', codigoProcedimento: '29', titulo: 'Comunicado malha energia', situacao: 'set' as const, diasParado: 3, etapaAtual: 3, etapasTotal: 6, proximaAcao: 'Conciliação de NF-e', responsavel: 'Carla', prazoInterno: '12/10/2026', prazoExterno: '26/10/2026', dataCiencia: '26/09/2026', fundamentoPrazo: '30 dias da ciência — comunicado SEFAZ (DT-e)', motivoAguardando: 'Conciliação de NF-e de compra de energia', setorAguardando: 'Fiscal', demandaOrigemId: 'D-057', orgao: 'SEFAZ-BA', ultimaAtualizacao: '30/09' },
  { id: 'P-115', clienteId: 'tec', clienteNome: 'Techsale Comércio', cnpj: '78.901.234/0001-56', estabelecimento: 'Matriz', codigoProcedimento: '10', titulo: 'Renovação de certificado e-CNPJ', situacao: 'cli' as const, diasParado: 1, etapaAtual: 3, etapasTotal: 6, proximaAcao: 'Agendar validação com a titular', responsavel: 'Ana', prazoInterno: '14/10/2026', prazoExterno: '20/10/2026', fundamentoPrazo: 'Vencimento do certificado e-CNPJ A1', motivoAguardando: 'Data para validação com Mônica Prado', demandaOrigemId: 'D-058', orgao: 'Certificadora', ultimaAtualizacao: '01/10' },
  { id: 'P-098', clienteId: 'atl', clienteNome: 'Atlântico Distribuidora', cnpj: '12.345.678/0001-90', estabelecimento: 'Filial', codigoProcedimento: '04', titulo: 'Abertura de filial — Camaçari', situacao: 'conc' as const, diasParado: 0, etapaAtual: 6, etapasTotal: 6, proximaAcao: '', responsavel: 'Matheus', prazoInterno: '', dataConclusao: '25/09/2026', marcos: [{ tipo: 'Deferido' as const, data: '19/09' }], orgao: 'JUCEB', ultimaAtualizacao: '25/09' },
  { id: 'P-099', clienteId: 'ges', clienteNome: 'Gesso Forte', cnpj: '23.456.789/0001-01', estabelecimento: 'Matriz', codigoProcedimento: '18', titulo: 'Certidão federal', situacao: 'conc' as const, diasParado: 0, etapaAtual: 6, etapasTotal: 6, proximaAcao: '', responsavel: 'Ana', prazoInterno: '', dataConclusao: '28/09/2026', orgao: 'Receita', ultimaAtualizacao: '28/09' },
  { id: 'P-097', clienteId: 'atl', clienteNome: 'Atlântico Distribuidora', cnpj: '12.345.678/0001-90', estabelecimento: 'Matriz', codigoProcedimento: '31', titulo: 'Regime especial renovado', situacao: 'conc' as const, diasParado: 0, etapaAtual: 6, etapasTotal: 6, proximaAcao: '', responsavel: 'Matheus', prazoInterno: '', dataConclusao: '22/09/2026', marcos: [{ tipo: 'Deferido' as const, data: '22/09' }], orgao: 'SEFAZ-BA', ultimaAtualizacao: '22/09' }
];

export const GUIAS_SEED = [
  { id: 'g1', clienteNome: 'Spazio Comércio', cnpj: '34.567.890/0001-12', orgao: 'SEFAZ-BA', modalidade: 'Estadual ICMS', numeroAcordo: 'PAF 2136870025', parcela: '8/24', vencimento: '30/10', valor: 1842.10, origem: 'Portal SEFAZ', statusGuia: 'emitir' as const, contatoEnvio: 'Tânia Vieira · WhatsApp', tributo: 'ICMS 2023–2024', etapasConferencia: [false, false, false, false, false, false] },
  { id: 'g2', clienteNome: 'Techsale Comércio', cnpj: '78.901.234/0001-56', orgao: 'Receita', modalidade: 'Simplificado', numeroAcordo: '12.345.678', parcela: '15/60', vencimento: '30/10', valor: 612.40, origem: 'Jettax', statusGuia: 'enviada' as const, contatoEnvio: 'Mônica Prado · e-mail', tributo: 'IRPJ/CSLL 2024', etapasConferencia: [true, true, true, true, true, true], dataEnvio: '01/10 · E-mail' },
  { id: 'g3', clienteNome: 'Techsale Comércio', cnpj: '78.901.234/0001-56', orgao: 'PGFN', modalidade: 'Transação', numeroAcordo: '9876543', parcela: '22/120', vencimento: '30/10', valor: 389.90, origem: 'Jettax não trouxe', statusGuia: 'emitir' as const, contatoEnvio: 'Mônica Prado · e-mail', tributo: 'Dívida ativa 2022–2023', etapasConferencia: [false, false, false, false, false, false] },
  { id: 'g4', clienteNome: 'Gesso Forte', cnpj: '23.456.789/0001-01', orgao: 'Simples Nacional', modalidade: 'Convencional', numeroAcordo: '2025000123', parcela: '11/60', vencimento: '30/10', valor: 455.77, origem: 'Jettax', statusGuia: 'paga' as const, contatoEnvio: 'Márcio Reis · WhatsApp', tributo: 'DAS 2024', etapasConferencia: [true, true, true, true, true, true], dataEnvio: '30/09 · WhatsApp', dataPagamento: '01/10' },
  { id: 'g5', clienteNome: 'V25 Serviços', cnpj: '45.678.901/0001-23', orgao: 'Simples Nacional', modalidade: 'PERT-SN', numeroAcordo: '2018004567', parcela: '87/120', vencimento: '30/10', valor: 301.15, origem: 'Portal Simples', statusGuia: 'emitida' as const, contatoEnvio: 'Rose Santos · WhatsApp', tributo: 'DAS 2015–2017', etapasConferencia: [true, true, true, true, true, true] },
  { id: 'g6', clienteNome: 'Antônio & Filho', cnpj: '90.123.456/0001-78', orgao: 'Prefeitura de Salvador', modalidade: 'Municipal/REFIS', numeroAcordo: '77788', parcela: '5/12', vencimento: '10/10', valor: 980.00, origem: 'Portal Salvador', statusGuia: 'enviada' as const, contatoEnvio: 'Rose Almeida · e-mail', tributo: 'ISS/TFF 2023', etapasConferencia: [true, true, true, true, true, true], dataEnvio: '29/09 · E-mail' },
  { id: 'g7', clienteNome: 'Loyola Fonoaudiologia', cnpj: '56.789.012/0001-34', orgao: 'Receita', modalidade: 'Previdenciário', numeroAcordo: '55.443.322', parcela: '3/60', vencimento: '30/10', valor: 274.30, origem: 'Jettax', statusGuia: 'baixada' as const, contatoEnvio: 'Graziela Loyola · e-mail', tributo: 'Contribuições previdenciárias 2025', etapasConferencia: [true, true, true, true, true, true], dataEnvio: '28/09 · E-mail', dataPagamento: '30/09' },
  { id: 'g8', clienteNome: 'Atlântico Distribuidora', cnpj: '12.345.678/0001-90', orgao: 'Simples Nacional', modalidade: 'RELP', numeroAcordo: '2022009988', parcela: '30/180', vencimento: '30/10', valor: 1120.00, origem: 'Portal Simples', statusGuia: 'emitir' as const, contatoEnvio: 'Hugo Andrade · WhatsApp', tributo: 'DAS 2019–2021', situacaoAcordo: 'Em atraso' as const, etapasConferencia: [false, false, false, false, false, false] }
];
